<?php

return [

    'age' => [
        '0to3'   => '0 - 3 ans',
        '3to6'   => '3 - 6 ans',
        '6to12'  => '6 - 12 ans',
        '12to14' => '12 - 14 ans',
        '0to99'  => '0 - 99 ans',
        'other'  => 'Diverses',
    ],

    'workshop_status' => [
        '1' => 'En attente',
        '2' => 'Accepté',
        '3' => 'Passé',
        '4' => 'Annulé',
        '5' => 'Autre',
    ],

    'workshop_org_type' => [
        '1' => 'un particulier',
        '2' => 'un professionnel',
        '3' => 'une association',
    ],

    'rate_status' => [
        '1' => 'Valide',
        '2' => 'Annulé',
    ],

    'regions' => [
        'Alsace'                      => ['67', '68'],
        'Aquitaine'                   => ['40', '47', '33', '24', '64'],
        'Auvergne'                    => ['43', '03', '15', '63'],
        'Basse-normandie'             => ['14', '61', '50'],
        'Bourgogne'                   => ['21', '58', '71', '89'],
        'Bretagne'                    => ['29', '35', '22', '56'],
        'Centre'                      => ['45', '37', '41', '28', '36', '18'],
        'Champagne-ardenne'           => ['10', '08', '52', '51'],
        'Corse'                       => ['2B', '2A'],
        'Franche-compte'              => ['39', '25', '70', '90'],
        'Haute-normandie'             => ['27', '76'],
        'Languedoc-roussillon'        => ['48', '30', '34', '11', '66'],
        'Limousin'                    => ['19', '23', '87'],
        'Lorraine'                    => ['55', '54', '57', '88'],
        'Midi-pyrennees'              => ['46', '32', '31', '12', '09', '65', '81', '82'],
        'Nord-pas-de-calais'          => ['62', '59'],
        'Pays-de-la-loire'            => ['49', '44', '72', '53', '85'],
        'Picardie'                    => ['02', '60', '80'],
        'Poitou-charentes'            => ['17', '16', '86', '79'],
        'Provences-alpes-cote-dazur'  => ['04', '05', '06', '13', '84', '83'],
        'Rhones-alpes'                => ['38', '42', '26', '07', '01', '74', '73', '69'],
        'Ile-de-france'               => ['77', '75', '78', '93', '92', '91', '95', '94'],
    ],

    'departments' => [
        '01'  => 'Ain',
        '02'  => 'Aisne',
        '03'  => 'Allier',
        '04'  => 'Alpes-de-Haute-Provence',
        '05'  => 'Hautes-Alpes',
        '06'  => 'Alpes-Maritimes',
        '07'  => 'Ardèche',
        '08'  => 'Ardennes',
        '09'  => 'Ariège',
        '10'  => 'Aube',
        '11'  => 'Aude',
        '12'  => 'Aveyron',
        '13'  => 'Bouches-du-Rhône',
        '14'  => 'Calvados',
        '15'  => 'Cantal',
        '16'  => 'Charente',
        '17'  => 'Charente-Maritime',
        '18'  => 'Cher',
        '19'  => 'Corrèze',
        '21'  => "Côte-d'Or",
        '22'  => "Côtes d'Armor",
        '23'  => 'Creuse',
        '24'  => 'Dordogne',
        '25'  => 'Doubs',
        '26'  => 'Drôme',
        '27'  => 'Eure',
        '28'  => 'Eure-et-Loir',
        '29'  => 'Finistère',
        '2A'  => 'Corse-du-Sud',
        '2B'  => 'Haute-Corse',
        '30'  => 'Gard',
        '31'  => 'Haute-Garonne',
        '32'  => 'Gers',
        '33'  => 'Gironde',
        '34'  => 'Hérault',
        '35'  => 'Ille-et-Vilaine',
        '36'  => 'Indre',
        '37'  => 'Indre-et-Loire',
        '38'  => 'Isère',
        '39'  => 'Jura',
        '40'  => 'Landes',
        '41'  => 'Loir-et-Cher',
        '42'  => 'Loire',
        '43'  => 'Haute-Loire',
        '44'  => 'Loire-Atlantique',
        '45'  => 'Loiret',
        '46'  => 'Lot',
        '47'  => 'Lot-et-Garonne',
        '48'  => 'Lozère',
        '49'  => 'Maine-et-Loire',
        '50'  => 'Manche',
        '51'  => 'Marne',
        '52'  => 'Haute-Marne',
        '53'  => 'Mayenne',
        '54'  => 'Meurthe-et-Moselle',
        '55'  => 'Meuse',
        '56'  => 'Morbihan',
        '57'  => 'Moselle',
        '58'  => 'Nièvre',
        '59'  => 'Nord',
        '60'  => 'Oise',
        '61'  => 'Orne',
        '62'  => 'Pas-de-Calais',
        '63'  => 'Puy-de-Dôme',
        '64'  => 'Pyrénées-Atlantiques',
        '65'  => 'Hautes-Pyrénées',
        '66'  => 'Pyrénées-Orientales',
        '67'  => 'Bas-Rhin',
        '68'  => 'Haut-Rhin',
        '69'  => 'Rhône',
        '70'  => 'Haute-Saône',
        '71'  => 'Saône-et-Loire',
        '72'  => 'Sarthe',
        '73'  => 'Savoie',
        '74'  => 'Haute-Savoie',
        '75'  => 'Paris',
        '76'  => 'Seine-Maritime',
        '77'  => 'Seine-et-Marne',
        '78'  => 'Yvelines',
        '79'  => 'Deux-Sèvres',
        '80'  => 'Somme',
        '81'  => 'Tarn',
        '82'  => 'Tarn-et-Garonne',
        '83'  => 'Var',
        '84'  => 'Vaucluse',
        '85'  => 'Vendée',
        '86'  => 'Vienne',
        '87'  => 'Haute-Vienne',
        '88'  => 'Vosges',
        '89'  => 'Yonne',
        '90'  => 'Territoire de Belfort',
        '91'  => 'Essonne',
        '92'  => 'Hauts-de-Seine',
        '93'  => 'Seine-St-Denis',
        '94'  => 'Val-de-Marne',
        '95'  => "Val-D'Oise",
        '971' => 'Guadeloupe',
        '972' => 'Martinique',
        '973' => 'Guyane',
        '974' => 'Réunion',
        '975' => 'Saint-Pierre-et-Miquelon',
        '976' => 'Mayotte',
        '984' => 'Terres Australes et Antarctiques',
        '986' => 'Wallis-et-Futuna',
        '987' => 'Polynésie française',
        '988' => 'Nouvelle-Calédonie',
    ],

];
